export const exampleResponse = {
  name: "Yogurt with Fruit, Protein, and Granola",
  ingredients: [
    {
      name: "Greek Yogurt",
      amount: "200",
      carbs: 10,
      proteins: 20,
      fats: 5,
    },
    {
      name: "Banana",
      amount: "90",
      carbs: 23,
      proteins: 1,
      fats: 0.3,
    },
    {
      name: "Strawberry",
      amount: "50",
      carbs: 4,
      proteins: 0.5,
      fats: 0.1,
    },
    {
      name: "Blueberry",
      amount: "25",
      carbs: 3.5,
      proteins: 0.3,
      fats: 0.1,
    },
    {
      name: "Raspberry",
      amount: "20",
      carbs: 1.5,
      proteins: 0.4,
      fats: 0.1,
    },
    {
      name: "Granola",
      amount: "60",
      carbs: 36,
      proteins: 5,
      fats: 4,
    },
    {
      name: "Hydrolised Whey Protein",
      amount: "30",
      carbs: 0,
      proteins: 25,
      fats: 0.5,
    },
    {
      name: "Collagen Peptides",
      amount: "10",
      carbs: 0,
      proteins: 9,
      fats: 0,
    },
  ],
};
